# Site settings
title: Tuan Q. Dinh
email: tuan.dinh@ucsf.edu
description: Academic webpage of Tuan Dinh
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Tuan Q. Dinh<br/>
    Postdoc Scholar<br/>
    University of California, San Francisco

location: >
  University of California, San Francisco<br/>
  513 Parnassus Avenue, Room #1263<br/>
  San Francisco, CA 94143

contact: >
    <a href="mailto:tuan.dinh@ucsf.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Tuan via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  # - name: talks
  - name: research
  - name: software
  - name: misc
  # - name: team
  # - name: teaching

include:
  - .htaccess
  - _pages

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - update_boostrap.sh
#   - switch_theme.sh
#   - tags
#   - Rakefile
